// <auto-generated />
namespace RecipeBox.ConsoleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DropAccountIdFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropAccountIdFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201406140434052_DropAccountIdFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
