// <auto-generated />
namespace RecipeBox.ConsoleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddRecipeSourceProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRecipeSourceProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201404242001056_AddRecipeSourceProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
